### PR TITLE
Added a restart method, changed unmonitor action, as this didn't work…

### PR DESCRIPTION
**Pull request by Rumbles**
… for me, bumped version in setup.py

### CODE REVIEW

**Comment by Rumbles** [comment]
I tested this on ubuntu 14.04 with monit daemon 5.6

**Comment by polymeris** [comment]
Thanks, I'll try to have a look at it this evening.

**Comment by Rumbles** [comment]
Thanks, I have 1 issue I am still struggling with. I feel the update method will return before the response from monit has been updated. Since some services we have might take a few seconds to stop or start, the update may have completed before the service state has changed.

I was hoping the pending action field might be useful here, but it always seems to be 0 in my testing.

I will persist though :)

**Comment by Rumbles** [comment]
I've found a way to continue checking the monit xml to ensure the stop() and start() doesn't return until the pending actions have completed. This means that the running command will return the state correctly and you don't have to keep checking the running state separately.

**Comment by Rumbles** [comment]
I'm aware that my method could run in to a recursion error, which is why I put the sleep in there, since python has a recursion limit of 999, this would have to run for 999 seconds before you hit the error. I can't see this being likely to ever occur. Monit should return in less than 15 minutes imo

**Comment by jamesridgway** [comment]
@polymeris - I'm also interested in this change. Is there anything that @Rumbles or I can do to help get this merged in and released?

Thanks.

**Pull request merged**
